language: go

go:
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

addons:
  postgresql: "9.3"

env:
  global:
    - PATH=$HOME/bin:$PATH
    - HAX=$(mkdir -p $HOME/bin ; cp /bin/echo $HOME/bin/gvm ; mkdir -p $HOME/.gvm/scripts ; touch $HOME/.gvm/scripts/gvm)
    - DATABASE_URL="postgres://localhost/book_development?sslmode=disable"

install:
  - export GOPATH=/home/travis/gopath
  - gimme ${TRAVIS_GO_VERSION}
  - source ~/.gimme/envs/go${TRAVIS_GO_VERSION}.env
  - go version
  - go env
