version: '3'
services:
  db:
    image: postgres
    volumes: 
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
       - ./db/migrate:/db/migrate/
    ports:
      - 5432:5432
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "book_api"]
    volumes:
      - .:/go/src/github.com/phanyzewski/book_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db